import { GraphEdge, WorkflowPath } from '@living-graph/extractor';

export class TestGenerator {
  /**
   * Generates a clean, production-grade Playwright TypeScript test spec.
   */
  public generateSpec(
    workflow: WorkflowPath,
    edges: GraphEdge[],
    baseUrl: string = 'http://localhost:5173',
    startRoute: string = '/login'
  ): string {
    const stepCodes = edges.map((edge, idx) => {
      return `
    // Step ${idx + 1}: ${edge.narration}
    // Action: ${edge.action.type} -> ${edge.action.targetSelector}
    ${edge.playwrightCode.split('\n').map((line: string) => `    ${line}`).join('\n')}
      `.trimEnd();
    }).join('\n\n');

    return `import { test, expect } from '@playwright/test';

/**
 * Auto-generated Playwright Test Spec
 * Workflow: ${workflow.title} (${workflow.id})
 * Generated by Living Graph Autonomous Walker
 */
test.describe('${workflow.title}', () => {
  test('should execute complete workflow successfully', async ({ page }) => {
    // Navigate to the workflow's actual starting screen
    await page.goto('${baseUrl}${startRoute}');

    ${stepCodes}
  });
});
`;
  }
}
